# Generated by Django 3.2.9 on 2021-12-06 12:54

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_delete_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='review',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='media'),
        ),
    ]
