# Generated by Django 3.2.9 on 2021-12-06 13:10

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20211206_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='media'),
        ),
    ]
