# Generated by Django 3.2.9 on 2021-12-06 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_review_images'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
    ]
